name: Docker Image CI for GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username develang --password ${{ secrets.GHP_BLOG }} ghcr.io
          docker build . --tag ghcr.io/develang/blog:latest
          docker push ghcr.io/develang/blog:latest
          docker build . --tag ghcr.io/develang/blog:${{ inputs.version }}
          docker push ghcr.io/develang/blog:${{ inputs.version }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          body: Body
